version: "3.9"

services:
  board:
    container_name: board
    build: ./board
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    volumes:
      - board_data:/app/data
      - ./board/logs:/var/log/app
    ports:
      - "50000:5000"

  monitor:
    container_name: monitor
    build: ./monitor
    command: gunicorn -w 4 -b 0.0.0.0:5001 app:app
    volumes:
      - ./monitor/logs:/var/log/app
    ports:
      - "50001:5001"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs:/var/log/nginx
    ports:
      - "50080:80"
    depends_on:
      - board
      - monitor

volumes:
  board_data:

